#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Dicionário de traduções oficiais / melhoradas para nomes de monstros.
Adicione quantas entradas quiser – o script 2b-traduzir-monster-names.py
dará sempre prioridade a este dicionário.
"""

MCR_MONSTERS = {
    "Frost Dragon": "Dragão da Nevada",
    "Frost Giant": "Gigante do Gelo",
    "Frost Giantess": "Gigante de Gelo",
    "Minotaur Poacher": "Caçador Furtivo Minotauro",
    "Cobra": "Cobra Peçonhenta",
    "Glooth Brigand": "Bandida Glooth",
    "Glooth Bandit": "Bandido Glooth",
    "Werelioness": "Lobisomen Leoa",
    # ---- criaturas que a API traduz mal ----
    "A Greedy Eye": "Olho Ganancioso",
    "A Shielded Astral Glyph": "Glifo Astral Blindado",
    "An Astral Glyph": "Glifo Astral",
    "An Observer Eye": "Olho Observador",
    "An Observer Eye (imune)": "Olho Observador (imune)",
    "Amazon": "Amazona",
    "Badger": "Texugo",
    "Bandit": "Bandido",
    "Banshee": "Banshee",
    "Bat": "Morcego",
    "Bear": "Urso",
    "Behemoth": "Beemote",
    "Black Knight": "Cavaleiro Negro",
    "Black Sheep": "Ovelha Negra",
    "Blood Crab": "Caranguejo de Sangue",
    "Blood Hand": "Mão de Sangue",
    "Blood Priest": "Sacerdote de Sangue",
    "Boar": "Javali",
    "Bog Frog": "Rã do Pântano",
    "Bog Raider": "Invasor do Lodo",
    "Bonelord": "Senhor dos Ossos",
    "Bug": "Inseto",
    "Butterfly": "Borboleta",
    "Carrion Worm": "Verme Carniceiro",
    "Cat": "Gato",
    "Cave Devourer": "Devorador de Cavernas",
    "Cave Rat": "Rato da Caverna",
    "Centipede": "Centopeia",
    "Chicken": "Galinha",
    "Clomp": "Clomp",
    "Cobra": "Cobra",
    "Cockroach": "Barata",
    "Coral Frog": "Rã Coral",
    "Crape Man": "Homem de Trapo",
    "Crazed Dwarf": "Anão Enlouquecido",
    "Crimson Frog": "Rã Carmesim",
    "Crocodile": "Crocodilo",
    "Cyclops": "Ciclope",
    "Dark Apprentice": "Aprendiz Sombrio",
    "Dark Magician": "Mago Negro",
    "Dark Monk": "Monge Sombrio",
    "Deer": "Cervo",
    "Demon": "Demônio",
    "Demon Skeleton": "Esqueleto Demoníaco",
    "Destroyer": "Destruidor",
    "Devourer": "Devorador",
    "Dog": "Cachorro",
    "Donkey": "Burro",
    "Dragon": "Dragão",
    "Dragon Hatchling": "Filhote de Dragão",
    "Dragon Lord": "Senhor dos Dragões",
    "Dragon Lord Hatchling": "Filhote do Senhor dos Dragões",
    "Dromedary": "Dromedário",
    "Dryad": "Dríade",
    "Dwarf": "Anão",
    "Dwarf Guard": "Guarda Anão",
    "Dwarf Miner": "Mineiro Anão",
    "Dwarf Soldier": "Soldado Anão",
    "Dworc Fleshhunter": "Caçador de Carne Dworc",
    "Dworc Venomsniper": "Atirador Venenoso Dworc",
    "Dworc Voodoomaster": "Mestre Vodu Dworc",
    "Earth Elemental": "Elemental da Terra",
    "Elephant": "Elefante",
    "Elf": "Elfo",
    "Elf Arcanist": "Arcanista Élfico",
    "Elf Scout": "Batedor Élfico",
    "Energy Elemental": "Elemental de Energia",
    "Evil Sheep": "Ovelha Má",
    "Evil Sheep Lord": "Senhor das Ovelhas Más",
    "Fire Devil": "Diabrete do Fogo",
    "Fire Elemental": "Elemental do Fogo",
    "Fish": "Peixe",
    "Flamingo": "Flamingo",
    "Fox": "Raposa",
    "Frost Troll": "Troll de Gelo",
    "Fury": "Fúria",
    "Gang Member": "Membro de Gangue",
    "Gargoyle": "Gárgula",
    "Ghost": "Aparição",
    "Ghoul": "Carniçal",
    "Giant Spider": "Aranha Gigante",
    "Gladiator": "Gladiador",
    "Gloom Wolf": "Lobo Sombrio",
    "Goblin": "Goblin",
    "Goblin Assassin": "Assassino Goblin",
    "Goblin Scavenger": "Catador Goblin",
    "Grave Guard": "Guarda de Cova",
    "Grave Robber": "Ladrão de Túmulos",
    "Green Djinn": "Djinn Verde",
    "Grey Horse": "Cavalo Cinza",
    "Grim Reaper": "Ceifador de Almas",
    "Hacker": "Hacker",
    "Haunted Treeling": "Árvore Assombrada",
    "Hero": "Herói",
    "Horse": "Cavalo",
    "Husky": "Husky",
    "Hyaena": "Hiena",
    "Hydra": "Hidra",
    "Ice Witch": "Bruxa do Gelo",
    "Infernalist": "Infernalista",
    "Island Troll": "Troll da Ilha",
    "Killer Caiman": "Jacaré Assassino",
    "Kongra": "Kongra",
    "Larva": "Larva",
    "Lich": "Lich",
    "Lion": "Leão",
    "Mammoth": "Mamute",
    "Manta Ray": "Arraia Manta",
    "Marid": "Marid",
    "Marsh Stalker": "Espreitador do Pântano",
    "Medusa": "Medusa",
    "Merlkin": "Merlkin",
    "Minotaur": "Minotauro",
    "Minotaur Archer": "Arqueiro Minotauro",
    "Minotaur Guard": "Guarda Minotauro",
    "Minotaur Mage": "Mago Minotauro",
    "Mole": "Toupeira",
    "Monk": "Monge",
    "Mummy": "Múmia",
    "Mutated Bat": "Morcego Mutante",
    "Mutated Human": "Humano Mutante",
    "Mutated Rat": "Rato Mutante",
    "Mutated Tiger": "Tigre Mutante",
    "Necromancer": "Necromante",
    "Nightmare": "Pesadelo",
    "Nomad": "Nômade",
    "Northern Pike": "Lúcio",
    "Nymph": "Ninfa",
    "Ogah": "Ogah",
    "Ogre": "Ogro",
    "Old Bear": "Urso Velho",
    "Orc": "Orc",
    "Orc Berserker": "Berserker Orc",
    "Orc Leader": "Líder Orc",
    "Orc Shaman": "Xamã Orc",
    "Orc Spearman": "Lanceiro Orc",
    "Orc Warlord": "Senhor da Guerra Orc",
    "Orc Warrior": "Guerreiro Orc",
    "Panda": "Panda",
    "Parrot": "Papagaio",
    "Penguin": "Pinguim",
    "Pig": "Porco",
    "Pigeon": "Pombo",
    "Pirate Buccaneer": "Bucaneiro Pirata",
    "Pirate Corsair": "Corsário Pirata",
    "Pirate Cutthroat": "Carrasco Pirata",
    "Pirate Ghost": "Fantasma Pirata",
    "Pirate Marauder": "Pilhador Pirata",
    "Pirate Skeleton": "Esqueleto Pirata",
    "Poacher": "Caçador Furtivo",
    "Poison Spider": "Aranha Peçonhenta",
    "Polar Bear": "Urso Polar",
    "Poodle": "Poodle",
    "Pooka": "Pooka",
    "Priestess": "Sacerdotisa",
    "Quara Constrictor": "Quara Constritora",
    "Quara Hydromancer": "Quara Hidromante",
    "Quara Mantassin": "Quara Mantassin",
    "Quara Pincher": "Quara Pinça",
    "Quara Predator": "Quara Predadora",
    "Rabbit": "Coelho",
    "Rat": "Rato",
    "Renegade Knight": "Cavaleiro Renegado",
    "Rotworm": "Verme da Podridão",
    "Scarab": "Escaravelho",
    "Scorpion": "Escorpião",
    "Sea Serpent": "Serpente Marinha",
    "Seagull": "Gaivota",
    "Shark": "Tubarão",
    "Sheep": "Ovelha",
    "Sibang": "Sibang",
    "Silver Rabbit": "Coelho Prateado",
    "Skeleton": "Esqueleto",
    "Skunk": "Gambá",
    "Slime": "Lodo",
    "Slug": "Lesma",
    "Smuggler": "Contrabandista",
    "Snake": "Cobra",
    "Spectre": "Espectro",
    "Spider": "Aranha",
    "Spit Nettle": "Urtiga Cuspideira",
    "Squirrel": "Esquilo",
    "Stalker": "Perseguidor",
    "Stone Golem": "Golem de Pedra",
    "Swamp Troll": "Troll do Pântano",
    "Tarantula": "Tarântula",
    "Terramite": "Terramita",
    "Terror Bird": "Pássaro do Terror",
    "Tiger": "Tigre",
    "Toad": "Sapo",
    "Tortoise": "Tartaruga",
    "Training Machine": "Máquina de Treino",
    "Troll": "Troll",
    "Troll Champion": "Troll Campeão",
    "Undead Cavebear": "Urso das Cavernas Morto-Vivo",
    "Undead Dragon": "Dragão Morto-Vivo",
    "Undead Gladiator": "Gladiador Morto-Vivo",
    "Valkyrie": "Valquíria",
    "Vampire": "Vampiro",
    "Vampire Bride": "Noiva Vampira",
    "Vampire Pig": "Porco Vampiro",
    "Vampire Viscount": "Visconde Vampiro",
    "Vicious Squire": "Escudeiro Vicioso",
    "Vile Grandmaster": "Grão-Mestre Vil",
    "Wasp": "Vespa",
    "Water Buffalo": "Búfalo Aquático",
    "Water Elemental": "Elemental da Água",
    "Weakened Demon": "Demônio Enfraquecido",
    "Werebadger": "Texugomem",
    "Werebear": "Ursomem",
    "Wereboar": "Javalomem",
    "Werewolf": "Lobisomem",
    "Wild Warrior": "Guerreiro Selvagem",
    "Witch": "Bruxa",
    "Wolf": "Lobo",
    "Worker Golem": "Golem Operário",
    "Wyrm": "Wyrm",
    "Wyvern": "Wyvern",
    "Zombie": "Zumbi",

    # ... todos os outros monstros que já apareceram no seu log e estavam correctos ...
    # (mantenha os que já estavam bons e adicione novas traduções sempre que necessário)
}

# Se um nome não estiver neste dicionário, a API será usada.