#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Dicionário de correções manuais para o Projeto MCR.
Substitui traduções automáticas erradas por termos oficiais do Tibia em português.
"""

MCR_CORRECTIONS = {
    # ===== ARMADURAS (Armors) =====
    "Knight Armor": "Armadura de Cavaleiro",
    "Knight Legs": "Calças de Cavaleiro",
    "Leather Armor": "Armadura de Couro",
    "Chain Armor": "Armadura de Malha",
    "Plate Armor": "Armadura de Placas",
    "Brass Armor": "Armadura de Latão",
    "Scale Armor": "Armadura de Escamas",
    "Studded Armor": "Armadura Cravejada",
    "Doublet": "Gibão",
    "Jacket": "Jaqueta",
    "Coat": "Casaco",
    "Cape": "Capa",
    "Robe": "Túnica",
    "Blue Robe": "Túnica Azul",
    "Red Robe": "Túnica Vermelha",
    "Green Robe": "Túnica Verde",
    "Dark Robe": "Túnica Negra",
    "Fire Robe": "Túnica de Fogo",
    "Wind Robe": "Túnica do Vento",
    "Golden Armor": "Armadura Dourada",
    "Demon Armor": "Armadura Demoníaca",
    "Dark Armor": "Armadura Sombria",
    "Magic Plate Armor": "Armadura Mágica de Placas",
    "Dragon Scale Mail": "Cota de Escamas de Dragão",
    "Noble Armor": "Armadura Nobre",
    "Crown Armor": "Armadura da Coroa",
    "Dwarven Armor": "Armadura Anã",
    "Elven Mail": "Cota de Malha Élfica",
    "Native Armor": "Armadura Nativa",
    "Leopard Armor": "Armadura de Leopardo",
    "Amazon Armor": "Armadura de Amazona",
    "Spirit Cloak": "Manto do Espírito",
    "Focus Cape": "Capa de Foco",
    "Belted Cape": "Capa com Cinto",
    "Lavos Armor": "Armadura de Lavos",
    "Crystalline Armor": "Armadura Cristalina",
    "Voltage Armor": "Armadura de Voltagem",
    "Swamplair Armor": "Armadura do Charco",
    "Yalahari Armor": "Armadura Yalahari",
    "Depth Lorica": "Lórica das Profundezas",
    "Gill Coat": "Casaco Branquial",
    "Gill Legs": "Calças Branquiais",
    "Dream Shroud": "Mortalha do Sonho",
    "Living Armor": "Armadura Viva",

    # ===== CAPACETES (Helmets) =====
    "Leather Helmet": "Capacete de Couro",
    "Chain Helmet": "Capacete de Malha",
    "Iron Helmet": "Capacete de Ferro",
    "Steel Helmet": "Capacete de Aço",
    "Brass Helmet": "Capacete de Latão",
    "Viking Helmet": "Capacete Viking",
    "Warrior Helmet": "Capacete de Guerreiro",
    "Crusader Helmet": "Capacete de Cruzado",
    "Royal Helmet": "Capacete Real",
    "Demon Helmet": "Capacete Demoníaco",
    "Horned Helmet": "Capacete com Chifres",
    "Winged Helmet": "Capacete Alado",
    "Crown Helmet": "Capacete da Coroa",
    "Dragon Scale Helmet": "Capacete de Escamas de Dragão",
    "Dark Helmet": "Capacete Sombrio",
    "Mage Hat": "Chapéu de Mago",
    "Magician Hat": "Chapéu de Mágico",
    "Mystic Turban": "Turbante Místico",
    "Jester Hat": "Chapéu do Bobo",
    "Witch Hat": "Chapéu de Bruxa",
    "Cobra Hood": "Capuz de Naja",
    "Falcon Circlet": "Diadema do Falcão",
    "Falcon Coif": "Capuz do Falcão",
    "Gnome Helmet": "Capacete Gnomo",
    "Prismatic Helmet": "Capacete Prismático",
    "Yalahari Mask": "Máscara Yalahari",
    "Depth Galea": "Gálea das Profundezas",

    # ===== ESCUDOS (Shields) =====
    "Wooden Shield": "Escudo de Madeira",
    "Studded Shield": "Escudo Cravejado",
    "Plate Shield": "Escudo de Placas",
    "Brass Shield": "Escudo de Latão",
    "Steel Shield": "Escudo de Aço",
    "Battle Shield": "Escudo de Batalha",
    "Dragon Shield": "Escudo do Dragão",
    "Demon Shield": "Escudo Demoníaco",
    "Crown Shield": "Escudo da Coroa",
    "Dark Shield": "Escudo Sombrio",
    "Guardian Shield": "Escudo Guardião",
    "Mastermind Shield": "Escudo do Mestre",
    "Ornamented Shield": "Escudo Ornamentado",
    "Beholder Shield": "Escudo de Beholder",
    "Vampire Shield": "Escudo do Vampiro",
    "Phoenix Shield": "Escudo da Fênix",
    "Necromancer Shield": "Escudo do Necromante",
    "Rift Shield": "Escudo da Fenda",
    "Carapace Shield": "Escudo de Carapaça",
    "Ectoplasmic Shield": "Escudo Ectoplásmico",
    "Falcon Shield": "Escudo do Falcão",
    "Falcon Escutcheon": "Brasão do Falcão",
    "Gnome Shield": "Escudo Gnomo",
    "Shield of Care": "Escudo do Cuidado",
    "Shield of the White Knight": "Escudo do Cavaleiro Branco",

    # ===== PERNAS (Legs) =====
    "Leather Legs": "Calças de Couro",
    "Chain Legs": "Calças de Malha",
    "Plate Legs": "Calças de Placas",
    "Brass Legs": "Calças de Latão",
    "Studded Legs": "Calças Cravejadas",
    "Crown Legs": "Calças da Coroa",
    "Demon Legs": "Calças Demoníacas",
    "Golden Legs": "Calças Douradas",
    "Dragon Scale Legs": "Calças de Escamas de Dragão",
    "Dwarven Legs": "Calças Anãs",
    "Elven Legs": "Calças Élficas",
    "Bast Skirt": "Saia de Entrecasca",
    "Terra Legs": "Calças de Terra",
    "Magma Legs": "Calças de Magma",
    "Lightning Legs": "Calças de Raio",
    "Glacier Kilt": "Saiote do Glaciar",
    "Ornate Legs": "Calças Ornadas",
    "Prismatic Legs": "Calças Prismáticas",
    "Gnome Legs": "Calças Gnômicas",
    "Falcon Greaves": "Grevas do Falcão",

    # ===== BOTAS (Boots) =====
    "Leather Boots": "Botas de Couro",
    "Steel Boots": "Botas de Aço",
    "Golden Boots": "Botas Douradas",
    "Crocodile Boots": "Botas de Crocodilo",
    "Boots of Haste": "Botas da Pressa",
    "Soft Boots": "Botas Macias",
    "Bunnys Slippers": "Pantufas de Coelho",
    "Fur Boots": "Botas de Pele",
    "Patched Boots": "Botas Remendadas",
    "Worn Leather Boots": "Botas de Couro Usadas",
    "Pirate Boots": "Botas de Pirata",
    "Crystal Boots": "Botas de Cristal",
    "Dragon Scale Boots": "Botas de Escamas de Dragão",
    "Guardian Boots": "Botas do Guardião",
    "Draken Boots": "Botas Drakens",
    "Cobra Boots": "Botas de Naja",
    "Dreamwalkers": "Andarilhas dos Sonhos",
    "Prismatic Boots": "Botas Prismáticas",
    "Void Boots": "Botas do Vazio",
    "Zaoan Shoes": "Sapatos Zaoan",

    # ===== ARMAS DE ESPADA (Swords) =====
    "Sword": "Espada",
    "Dagger": "Adaga",
    "Knife": "Faca",
    "Combat Knife": "Faca de Combate",
    "Silver Dagger": "Adaga de Prata",
    "Poison Dagger": "Adaga Envenenada",
    "Rapier": "Rapieira",
    "Sabre": "Sabre",
    "Short Sword": "Espada Curta",
    "Longsword": "Espada Longa",
    "Broadsword": "Espada Larga",
    "Scimitar": "Cimitarra",
    "Katana": "Katana",
    "Serpent Sword": "Espada da Serpente",
    "Spike Sword": "Espada de Espinhos",
    "Fire Sword": "Espada de Fogo",
    "Ice Rapier": "Rapieira de Gelo",
    "Giant Sword": "Espada Gigante",
    "Two Handed Sword": "Espada de Duas Mãos",
    "Bright Sword": "Espada Brilhante",
    "Magic Long Sword": "Espada Longa Mágica",
    "Magic Sword": "Espada Mágica",
    "Warlord Sword": "Espada do Senhor da Guerra",
    "Epee": "Espada",
    "Zaoan Sword": "Espada Zaoan",
    "Falcon Longsword": "Espada Longa do Falcão",
    "Cobra Sword": "Espada de Naja",
    "Summerblade": "Lâmina do Verão",
    "Winterblade": "Lâmina do Inverno",
    "Umbral Blade": "Lâmina Umbral",
    "Umbral Masterblade": "Superlâmina Umbral",
    "Shiny Blade": "Lâmina Reluzente",

    # ===== ARMAS DE MACHADO (Axes) =====
    "Axe": "Machado",
    "Hand Axe": "Machado de Mão",
    "Hatchet": "Machadinha",
    "Orcish Axe": "Machado Orc",
    "Barbarian Axe": "Machado Bárbaro",
    "Knight Axe": "Machado de Cavaleiro",
    "Stonecutter Axe": "Machado Corta-Pedra",
    "Dwarven Axe": "Machado Anão",
    "Daramian Axe": "Machado Daramiano",
    "Fire Axe": "Machado de Fogo",
    "Battle Axe": "Machado de Batalha",
    "Double Axe": "Machado Duplo",
    "Dragon Lance": "Lança de Dragão",
    "Halberd": "Alabarda",
    "Guardian Halberd": "Alabarda Guardiã",
    "Twin Axe": "Machado Gêmeo",
    "Great Axe": "Grande Machado",
    "Ravagers Axe": "Machado do Devastador",
    "War Axe": "Machado de Guerra",
    "Ripper Lance": "Lança Estripadora",
    "Naginata": "Naginata",
    "Obsidian Lance": "Lança de Obsidiana",
    "Daramian Waraxe": "Machado de Guerra Daramiano",
    "Heavy Trident": "Tridente Pesado",
    "Deepling Axe": "Machado dos Depths",
    "Zaoan Halberd": "Alabarda Zaoan",
    "Cobra Axe": "Machado de Naja",
    "Falcon Battleaxe": "Machado de Batalha do Falcão",
    "Crystalline Axe": "Machado Cristalino",
    "Umbral Axe": "Machado Umbral",
    "Umbral Master Axe": "Supermachado Umbral",

    # ===== ARMAS DE CLAVA (Clubs) =====
    "Club": "Clava",
    "Studded Club": "Clava Cravejada",
    "Bone Club": "Clava de Osso",
    "Mace": "Maça",
    "Light Mace": "Maça Leve",
    "Clerical Mace": "Maça Clerical",
    "Silver Mace": "Maça de Prata",
    "Crystal Mace": "Maça de Cristal",
    "War Hammer": "Martelo de Guerra",
    "Thunder Hammer": "Martelo de Trovão",
    "Dragon Hammer": "Martelo de Dragão",
    "Iron Hammer": "Martelo de Ferro",
    "Heavy Mace": "Maça Pesada",
    "Lich Staff": "Cajado Lich",
    "Skull Staff": "Cajado da Caveira",
    "Arcane Staff": "Cajado Arcano",
    "Lunar Staff": "Cajado Lunar",
    "Enchanted Staff": "Cajado Encantado",
    "Deepling Squelcher": "Esmagador das Profundezas",
    "Maimer": "Mutilador",
    "Cobra Club": "Clava de Naja",
    "Falcon Mace": "Maça do Falcão",
    "Umbral Mace": "Maça Umbral",
    "Umbral Master Mace": "Supermaça Umbral",
    "Hammer of Wrath": "Martelo da Ira",

    # ===== ARMAS À DISTÂNCIA (Distance Weapons) =====
    "Bow": "Arco",
    "Crossbow": "Balestra",
    "Spear": "Lança",
    "Throwing Star": "Estrela de Arremesso",
    "Throwing Knife": "Faca de Arremesso",
    "Royal Spear": "Lança Real",
    "Hunting Spear": "Lança de Caça",
    "Enchanted Spear": "Lança Encantada",
    "Leafstar": "Estrela de Folha",
    "Assassin Star": "Estrela do Assassino",
    "Cobra Crossbow": "Balestra de Naja",
    "Falcon Bow": "Arco do Falcão",
    "Umbral Bow": "Arco Umbral",
    "Umbral Master Bow": "Superarco Umbral",
    "Umbral Crossbow": "Balestra Umbral",
    "Umbral Master Crossbow": "Superbalestra Umbral",
    "Hive Bow": "Arco da Colmeia",
    "Ornate Crossbow": "Balestra Ornada",
    "Mycological Bow": "Arco Micológico",
    "Spitter": "Cuspidor",
    "Thorn Spitter": "Cuspidor de Espinhos",

    # ===== MUNIÇÃO (Ammunition) =====
    "Bolt": "Dardo de Besta",
    "Arrow": "Flecha",
    "Poison Arrow": "Flecha Envenenada",
    "Burst Arrow": "Flecha Explosiva",
    "Power Bolt": "Dardo Poderoso",
    "Earth Arrow": "Flecha de Terra",
    "Shiver Arrow": "Flecha de Gelo",
    "Flaming Arrow": "Flecha Flamejante",
    "Sniper Arrow": "Flecha de Atirador",
    "Onyx Arrow": "Flecha de Ônix",
    "Infernal Bolt": "Dardo Infernal",
    "Crystalline Arrow": "Flecha Cristalina",
    "Diamond Arrow": "Flecha de Diamante",
    "Spectral Bolt": "Dardo Espectral",
    "Royal Star": "Estrela Real",
    "Stone": "Pedra",
    "Small Stone": "Pedra Pequena",
    "Flash Arrow": "Flecha de Luz",
    "Energy Arrow": "Flecha de Energia",

    # ===== VARINHAS, BASTÕES & LIVROS DE MAGIA (Wands, Rods, Spellbooks) =====
    "Wand": "Varinha",
    "Rod": "Bastão",
    "Spellbook": "Livro de Feitiços",
    "Wand of Darkness": "Varinha das Trevas",
    "Wand of Inferno": "Varinha do Inferno",
    "Wand of Dragonbreath": "Varinha do Sopro do Dragão",
    "Crystal Wand": "Varinha de Cristal",
    "Dream Blossom Staff": "Cajado da Flor dos Sonhos",
    "Energized Limb": "Membro Energizado",
    "Shoulder Plate": "Ombros de Placa",
    "Brain in a Jar": "Cérebro em um Jarro",
    "Snake Gods Wristguard": "Braçadeira do Deus Serpente",
    "Deepling Ceremonial Dagger": "Adaga Cerimonial dos Depths",
    "Deepling Fork": "Garfo dos Depths",
    "Light Sphere": "Esfera de Luz",
    "Lit Light Sphere": "Esfera de Luz Acesa",
    "Ferumbras Staff": "Cajado de Ferumbras",
    "Necromancer Shield": "Escudo de Necromante",
    "Nightmare Shield": "Escudo do Pesadelo",

    # ===== AMULETOS E COLARES (Amulets and Necklaces) =====
    "Bronze Amulet": "Amuleto de Bronze",
    "Silver Amulet": "Amuleto de Prata",
    "Golden Amulet": "Amuleto Dourado",
    "Platinum Amulet": "Amuleto de Platina",
    "Sapphire Amulet": "Amuleto de Safira",
    "Ruby Necklace": "Colar de Rubi",
    "Crystal Necklace": "Colar de Cristal",
    "Scarab Amulet": "Amuleto de Escaravelho",
    "Demonbone Amulet": "Amuleto de Osso Demoníaco",
    "Garlic Necklace": "Colar de Alho",
    "Stone Skin Amulet": "Amuleto de Pele de Pedra",
    "Elven Amulet": "Amuleto Élfico",
    "Protection Amulet": "Amuleto de Proteção",
    "Amulet of Loss": "Amuleto da Perda",
    "Dragon Necklace": "Colar do Dragão",
    "Wolf Tooth Chain": "Colar de Dente de Lobo",
    "Star Amulet": "Amuleto Estrelado",
    "Strange Talisman": "Talismã Estranho",
    "Paw Amulet": "Amuleto da Pata",
    "Shrunken Head Necklace": "Colar de Cabeça Encolhida",
    "Rainbow Necklace": "Colar Arco-Íris",
    "Collar of Red Plasma": "Coleira de Plasma Vermelho",
    "Collar of Blue Plasma": "Coleira de Plasma Azul",
    "Collar of Green Plasma": "Coleira de Plasma Verde",
    "Enchanted Theurgic Amulet": "Amuleto Teúrgico Encantado",
    "Enchanted Sleep Shawl": "Xale do Sono Encantado",
    "Enchanted Pendulet": "Penduricalho Encantado",
    "Theurgic Amulet": "Amuleto Teúrgico",
    "Sleep Shawl": "Xale do Sono",
    "Pendulet": "Penduricalho",
    "Rubbish Amulet": "Amuleto de Lixo",
    "Glowing Rubbish Amulet": "Amuleto de Lixo Brilhante",

    # ===== ANÉIS (Rings) =====
    "Might Ring": "Anel do Poder",
    "Stealth Ring": "Anel da Furtividade",
    "Power Ring": "Anel do Poder",
    "Energy Ring": "Anel de Energia",
    "Life Ring": "Anel da Vida",
    "Time Ring": "Anel do Tempo",
    "Sword Ring": "Anel da Espada",
    "Axe Ring": "Anel do Machado",
    "Club Ring": "Anel da Clava",
    "Dwarven Ring": "Anel Anão",
    "Ring of Healing": "Anel da Cura",
    "Ring of Blue Plasma": "Anel de Plasma Azul",
    "Ring of Green Plasma": "Anel de Plasma Verde",
    "Ring of Red Plasma": "Anel de Plasma Vermelho",
    "Butterfly Ring": "Anel da Borboleta",
    "Ring of Secret Thoughts": "Anel dos Pensamentos Secretos",
    "Ring of Wishes": "Anel dos Desejos",
    "Ring of the Sky": "Anel do Céu",
    "Wedding Ring": "Aliança de Casamento",
    "Engraved Wedding Ring": "Aliança Gravada",
    "Crystal Ring": "Anel de Cristal",
    "Gold Ring": "Anel de Ouro",
    "Prismatic Ring": "Anel Prismático",

    # ===== POÇÕES (Potions) =====
    "Health Potion": "Poção de Vida",
    "Strong Health Potion": "Poção de Vida Forte",
    "Great Health Potion": "Poção de Vida Maior",
    "Ultimate Health Potion": "Poção de Vida Suprema",
    "Supreme Health Potion": "Poção de Vida Extrema",
    "Mana Potion": "Poção de Mana",
    "Strong Mana Potion": "Poção de Mana Forte",
    "Great Mana Potion": "Poção de Mana Maior",
    "Ultimate Mana Potion": "Poção de Mana Suprema",
    "Spirit Potion": "Poção de Espírito",
    "Great Spirit Potion": "Poção de Espírito Maior",
    "Ultimate Spirit Potion": "Poção de Espírito Supremo",
    "Antidote Potion": "Poção de Antídoto",
    "Berserk Potion": "Poção Furiosa",
    "Mastermind Potion": "Poção do Estrategista",
    "Bullseye Potion": "Poção de Precisão",

    # ===== RUNAS (Runes) =====
    "Blank Rune": "Runa em Branco",
    "Fire Field Rune": "Runa de Campo de Fogo",
    "Fireball Rune": "Runa de Bola de Fogo",
    "Great Fireball Rune": "Runa de Grande Bola de Fogo",
    "Fire Bomb Rune": "Runa de Bomba de Fogo",
    "Fire Wall Rune": "Runa de Parede de Fogo",
    "Explosion Rune": "Runa de Explosão",
    "Sudden Death Rune": "Runa de Morte Súbita",
    "Ultimate Healing Rune": "Runa de Cura Suprema",
    "Intense Healing Rune": "Runa de Cura Intensa",
    "Avalanche Rune": "Runa de Avalanche",
    "Icicle Rune": "Runa de Sincelo",
    "Thunderstorm Rune": "Runa de Tempestade",
    "Stone Shower Rune": "Runa de Chuva de Pedras",
    "Stalagmite Rune": "Runa de Estalagmite",
    "Heavy Magic Missile Rune": "Runa de Míssil Mágico Pesado",
    "Light Magic Missile Rune": "Runa de Míssil Mágico Leve",
    "Energy Field Rune": "Runa de Campo de Energia",
    "Energy Wall Rune": "Runa de Parede de Energia",
    "Energy Bomb Rune": "Runa de Bomba de Energia",
    "Paralyse Rune": "Runa de Paralisia",
    "Poison Field Rune": "Runa de Campo Venenoso",
    "Poison Bomb Rune": "Runa de Bomba Venenosa",
    "Poison Wall Rune": "Runa de Parede Venenosa",
    "Soulfire Rune": "Runa de Fogo da Alma",
    "Disintegrate Rune": "Runa de Desintegração",
    "Magic Wall Rune": "Runa de Parede Mágica",
    "Chameleon Rune": "Runa Camaleão",
    "Convince Creature Rune": "Runa de Convencimento",
    "Animate Dead Rune": "Runa de Animação de Mortos",
    "Destroy Field Rune": "Runa de Destruição de Campo",
    "Wild Growth Rune": "Runa de Crescimento Selvagem",
    "Holy Missile Rune": "Runa de Míssil Sagrado",

    # ===== OBJETOS DE VALOR (Valuables) =====
    "Gold Coin": "Moeda de Ouro",
    "Platinum Coin": "Moeda de Platina",
    "Crystal Coin": "Moeda de Cristal",
    "White Pearl": "Pérola Branca",
    "Black Pearl": "Pérola Negra",
    "Small Diamond": "Pequeno Diamante",
    "Small Emerald": "Pequena Esmeralda",
    "Small Ruby": "Pequeno Rubi",
    "Small Sapphire": "Pequena Safira",
    "Small Amethyst": "Pequena Ametista",
    "Small Topaz": "Pequeno Topázio",
    "Small Enchanted Ruby": "Pequeno Rubi Encantado",
    "Gold Ingot": "Lingote de Ouro",
    "Gold Nugget": "Pepita de Ouro",
    "Talon": "Garra",
    "Horn": "Chifre",
    "Green Gem": "Gema Verde",
    "Red Gem": "Gema Vermelha",
    "Yellow Gem": "Gema Amarela",
    "Blue Gem": "Gema Azul",
    "Violet Gem": "Gema Violeta",
    "Tiger Eye": "Olho de Tigre",
    "Prismatic Quartz": "Quartzo Prismático",
    "Rainbow Quartz": "Quartzo Arco-Íris",
    "Dragon Crown": "Coroa de Dragão",
    "Forbidden Fruit": "Fruto Proibido",
    "Frozen Time": "Tempo Congelado",
    "Key to Knowledge": "Chave do Conhecimento",
    "Shadow Mask": "Máscara da Sombra",
    "Shadow Paint": "Tinta Sombria",
    "Cobra Statue": "Estátua de Naja",
    "Sea Crest Pearl": "Pérola da Crista Marinha",

    # ===== ARTEFATOS MÁGICOS (Magical Items) =====
    "Ankh": "Ankh",
    "Blessed Ankh": "Ankh Abençoada",
    "Orb": "Orbe",
    "Crystal Ball": "Bola de Cristal",
    "Life Crystal": "Cristal da Vida",
    "Mind Stone": "Pedra da Mente",
    "Strange Symbol": "Símbolo Estranho",
    "Mysterious Fetish": "Fetiche Misterioso",
    "Demonbone": "Osso Demoníaco",
    "Soul Stone": "Pedra da Alma",
    "Holy Scarab": "Escaravelho Sagrado",
    "Holy Falcon": "Falcão Sagrado",
    "Ancient Amulet": "Amuleto Antigo",
    "Scarab Coin": "Moeda de Escaravelho",
    "Voodoo Doll": "Boneco Vodu",
    "Pirate Voodoo Doll": "Boneco Vodu Pirata",
    "Skull of Ratha": "Crânio de Ratha",
    "Ring of the Count": "Anel do Conde",
    "Ferumbras Hat": "Chapéu de Ferumbras",

    # ===== ALIMENTOS & BEBIDAS (Food & Drinks) =====
    "Meat": "Carne",
    "Ham": "Presunto",
    "Bread": "Pão",
    "Brown Bread": "Pão Integral",
    "Roll": "Pãozinho",
    "Cheese": "Queijo",
    "Fish": "Peixe",
    "Salmon": "Salmão",
    "Trout": "Truta",
    "Northern Pike": "Lúcio do Norte",
    "Shrimp": "Camarão",
    "Grapes": "Uvas",
    "Apple": "Maçã",
    "Pear": "Pêra",
    "Banana": "Banana",
    "Cherry": "Cereja",
    "Blueberry": "Mirtilo",
    "Strawberry": "Morango",
    "Orange": "Laranja",
    "Lemon": "Limão",
    "Watermelon": "Melancia",
    "Melon": "Melão",
    "Pumpkin": "Abóbora",
    "Carrot": "Cenoura",
    "Tomato": "Tomate",
    "Cucumber": "Pepino",
    "Onion": "Cebola",
    "Peas": "Ervilhas",
    "Broccoli": "Brócolis",
    "Cauliflower": "Couve-Flor",
    "Corncob": "Milho",
    "Potato": "Batata",
    "Beetroot": "Beterraba",
    "Jalapeno Pepper": "Pimenta Jalapeño",
    "Pineapple": "Abacaxi",
    "Mango": "Manga",
    "Coconut": "Coco",
    "Prickly Pear": "Figo da Índia",
    "Dragonfruit": "Pitaya",
    "Egg": "Ovo",
    "Intestines": "Intestinos",
    "Glorious Intestines": "Intestinos Gloriosos",
    "Luminous Intestines": "Intestinos Luminosos",
    "Stuffed Toad": "Sapo Empalhado",
    "Ice Cream Cone": "Casquinha de Sorvete",
    "Candy": "Doce",
    "Chocolate": "Chocolate",
    "Gingerbreadman": "Boneco de Gengibre",

    # ===== FERRAMENTAS & UTILIDADES (Tools & Utilities) =====
    "Shovel": "Pá",
    "Pick": "Picareta",
    "Rope": "Corda",
    "Machete": "Facão",
    "Scythe": "Foice",
    "Sickle": "Foice Curta",
    "Knife": "Faca",
    "Kitchen Knife": "Faca de Cozinha",
    "Fork": "Garfo",
    "Spoon": "Colher",
    "Wooden Spoon": "Colher de Pau",
    "Broom": "Vassoura",
    "Witchesbroom": "Vassoura de Bruxa",
    "Fishing Rod": "Vara de Pesca",
    "Bucket": "Balde",
    "Vial": "Frasco",
    "Waterskin": "Odre",
    "Bottle": "Garrafa",
    "Jug": "Jarra",
    "Mug": "Caneca",
    "Cup": "Xícara",
    "Bowl": "Tigela",
    "Pan": "Panela",
    "Pot": "Pote",
    "Rolling Pin": "Rolo de Massa",
    "Cleaver": "Cutelo",
    "Saw": "Serra",
    "Hammer": "Martelo",
    "Wooden Hammer": "Martelo de Madeira",
    "Torch": "Tocha",
    "Rope Belt": "Cinto de Corda",
    "Watch": "Relógio",
    "Magical Watch": "Relógio Mágico",
    "Oil Lamp": "Lâmpada a Óleo",
    "Mirror": "Espelho",
    "Telescope": "Telescópio",
    "Backpack": "Mochila",
    "Bag": "Bolsa",
    "Basket": "Cesta",
    "Purse": "Bolsa de Moedas",
    "Lock Pick": "Pé de Cabra",
    "Scrubbing Brush": "Escova de Limpeza",
    "Strange Device": "Dispositivo Estranho",
    "Golem Wrench": "Chave Inglesa de Golem",
    "Mechanical Fishing Rod": "Vara de Pesca Mecânica",
    "Universal Tool": "Ferramenta Universal",
    "Fairy Wand": "Varinha das Fadas",
    "Acid Resistant Fishing Rod": "Vara de Pesca Antiácida",

    # ===== CRIATURAS E CORPOS (Creatures & Corpses) =====
    "Dead Human": "Humano Morto",
    "Dead Rat": "Rato Morto",
    "Dead Spider": "Aranha Morta",
    "Dead Orc": "Orc Morto",
    "Dead Troll": "Troll Morto",
    "Dead Minotaur": "Minotauro Morto",
    "Dead Dragon": "Dragão Morto",
    "Dead Wyrm": "Serpe Morta",
    "Dead Hydra": "Hidra Morta",
    "Dead Sea Serpent": "Serpente Marinha Morta",
    "Dead Demon": "Demônio Morto",
    "Dead Fire Devil": "Diabrete de Fogo Morto",
    "Dead Behemoth": "Beemote Morto",
    "Dead Elf": "Elfo Morto",
    "Dead Dwarf": "Anão Morto",
    "Dead Cyclops": "Ciclope Morto",
    "Dead Ghoul": "Ghoul Morto",
    "Dead Mummy": "Múmia Morta",
    "Dead Vampire": "Vampiro Morto",
    "Dead Skeleton": "Esqueleto Morto",
    "Dead Lich": "Lich Morto",
    "Dead Bonelord": "Bonelord Morto",
    "Dead Crypt Shambler": "Vagante da Cripta Morto",
    "Dead Pharaoh": "Faraó Morto",
    "Dead Efreet": "Ifrit Morto",
    "Dead Marid": "Marid Morto",
    "Dead Djinn": "Djinn Morto",
    "Dead Ancient Scarab": "Escaravelho Antigo Morto",
    "Dead Scarab": "Escaravelho Morto",
    "Dead Cobra": "Naja Morta",
    "Dead Lion": "Leão Morto",
    "Dead Bear": "Urso Morto",
    "Dead Wolf": "Lobo Morto",
    "Dead Tiger": "Tigre Morto",
    "Dead Elephant": "Elefante Morto",
    "Dead Deer": "Cervo Morto",
    "Dead Crocodile": "Crocodilo Morto",
    "Dead Slime": "Limo Morto",
    "Dead Kongra": "Kongra Morto",
    "Dead Merlkin": "Merlkin Morto",
    "Dead Sibang": "Sibang Morto",
    "Dead Panda": "Panda Morto",
    "Dead Tortoise": "Tartaruga Morta",
    "Dead Toad": "Sapo Morto",
    "Dead Frog": "Rã Morta",
    "Dead Seagull": "Gaivota Morta",
    "Dead Parrot": "Papagaio Morto",
    "Dead Penguin": "Pinguim Morto",
    "Dead Husky": "Husky Morto",
    "Dead Crystal Wolf": "Lobo de Cristal Morto",
    "Dead Thornfire Wolf": "Lobo de Fogo Espinhoso Morto",
    "Dead War Wolf": "Lobo de Guerra Morto",
    "Dead Donkey": "Burro Morto",
    "Dead Pig": "Porco Morto",
    "Dead Sheep": "Ovelha Morta",
    "Dead Chicken": "Galinha Morta",
    "Dead Rabbit": "Coelho Morto",
    "Dead Swampling": "Pântaninho Morto",
    "Dead Frazzlemaw": "Frazzlemaw Morto",
    "Dead Guzzlemaw": "Guzzlemaw Morto",
    "Dead Silencer": "Silenciador Morto",
    "Dead Shock Head": "Cabeça de Choque Morta",
    "Dead Sphinx": "Esfinge Morta",
    "Dead Manticore": "Manticora Morta",

    # ===== PLANTAS & ERVAS (Plants & Herbs) =====
    "Red Rose": "Rosa Vermelha",
    "Blue Rose": "Rosa Azul",
    "Yellow Rose": "Rosa Amarela",
    "Flower Bouquet": "Buquê de Flores",
    "Moon Flower": "Flor da Lua",
    "White Flower": "Flor Branca",
    "Heaven Blossom": "Flor Celestial",
    "Grave Flower": "Flor do Túmulo",
    "Love Flower": "Flor do Amor",
    "Fern": "Samambaia",
    "Dandelion": "Dente-de-Leão",
    "Tulip": "Tulipa",
    "Orchid": "Orquídea",
    "Shadow Plant": "Planta das Sombras",
    "Blood Herb": "Erva de Sangue",
    "Stone Herb": "Erva de Pedra",
    "Star Herb": "Erva Estelar",
    "Sling Herb": "Erva do Funda",
    "Powder Herb": "Erva em Pó",
    "Shadow Herb": "Erva da Sombra",
    "Troll Green": "Verde de Troll",
    "Mandrake": "Mandrágora",
    "Carniphila Seeds": "Sementes de Carnívora",
    "Mushroom": "Cogumelo",
    "Red Mushroom": "Cogumelo Vermelho",
    "Brown Mushroom": "Cogumelo Marrom",
    "White Mushroom": "Cogumelo Branco",
    "Orange Mushroom": "Cogumelo Laranja",
    "Dark Mushroom": "Cogumelo Escuro",
    "Fire Mushroom": "Cogumelo de Fogo",
    "Green Mushroom": "Cogumelo Verde",
    "Fly Agaric": "Agárico-mosca",
    "Giggle Mushroom": "Cogumelo Risonho",
    "Holy Orchid": "Orquídea Sagrada",

    # ===== QUESTS, CHAVES E DOCUMENTOS (Quest Items, Keys, Documents) =====
    "Key": "Chave",
    "Silver Key": "Chave de Prata",
    "Golden Key": "Chave Dourada",
    "Copper Key": "Chave de Cobre",
    "Magical Key": "Chave Mágica",
    "Crystal Key": "Chave de Cristal",
    "Bone Key": "Chave de Osso",
    "Wooden Key": "Chave de Madeira",
    "Letter": "Carta",
    "Parcel": "Pacote",
    "Label": "Etiqueta",
    "Scroll": "Pergaminho",
    "Document": "Documento",
    "Map": "Mapa",
    "Book": "Livro",
    "Tome": "Tomo",
    "Diary": "Diário",
    "Notebook": "Caderno",
    "Piece of Paper": "Pedaço de Papel",
    "Blank Paper": "Papel em Branco",
    "Contract": "Contrato",
    "Signed Contract": "Contrato Assinado",
    "Parchment": "Pergaminho",
    "Old Parchment": "Pergaminho Velho",
    "Rubbish": "Lixo",
    "Chest": "Baú",
    "Crate": "Caixote",
    "Barrel": "Barril",
    "Box": "Caixa",
    "Trunk": "Baú Grande",
    "Backpack": "Mochila",
    "Bag": "Bolsa",
    "Present": "Presente",
    "Parcel": "Pacote",

    # ===== ITENS DIVERSOS (Miscellaneous) =====
    "Gold Converter": "Conversor de Ouro",
    "Ectoplasm Container": "Recipiente de Ectoplasma",
    "Spirit Container": "Recipiente de Espírito",
    "Flask of Cough Syrup": "Frasco de Xarope para Tosse",
    "Flask of Waterbinding": "Frasco de Vinculação de Água",
    "Flask of Embalming Fluid": "Frasco de Fluido de Embalsamamento",
    "Flask of Demonic Blood": "Frasco de Sangue Demoníaco",
    "Mysterious Metal Egg": "Ovo Metálico Misterioso",
    "Ancient Watch": "Relógio Antigo",
    "Golden Statue": "Estátua Dourada",
    "Silver Brooch": "Broche de Prata",
    "Crown": "Coroa",
    "Dwarven Beard": "Barba de Anão",
    "Fake Dwarven Beard": "Barba de Anão Falsa",
    "Dragon Claw": "Garra de Dragão",
    "Cyclops Toe": "Dedo do Pé de Ciclope",
    "Minotaur Horn": "Chifre de Minotauro",
    "Witches Cauldron": "Caldeirão de Bruxa",
    "Surprise Bag": "Bolsa Surpresa",
    "Party Trumpet": "Corneta de Festa",
    "Party Hat": "Chapéu de Festa",
    "Fireworks Rocket": "Foguete de Fogos de Artifício",
    "Snowball": "Bola de Neve",
    "Teddy Bear": "Ursinho de Pelúcia",
    "Doll": "Boneca",
    "Toy Mouse": "Ratinho de Brinquedo",
    "Rocking Horse": "Cavalo de Balanço",
    "Piggy Bank": "Cofrinho",
    "Broken Piggy Bank": "Cofrinho Quebrado",
    "Honeycomb": "Favo de Mel",
    "Bear Paw": "Pata de Urso",
    "Wolf Paw": "Pata de Lobo",
    "Bat Wing": "Asa de Morcego",
    "Fish Fin": "Barbatana de Peixe",
    "Turtle Shell": "Casco de Tartaruga",
    "Chicken Feather": "Pena de Galinha",
    "Enchanted Chicken Wing": "Asa de Frango Encantada",
    "Demon Dust": "Pó Demoníaco",
    "Vampire Dust": "Pó de Vampiro",
    "Magic Sulphur": "Enxofre Mágico",
    "Blank Rune": "Runa em Branco",
    "Spell Rune": "Runa de Feitiço",
    "Strange Rune": "Runa Estranha",
    "Incantation Scroll": "Pergaminho de Encantamento",
    "Seed": "Semente",
    "Vine": "Videira",
    "Wood": "Madeira",
    "Nail": "Prego",
    "Iron Ore": "Minério de Ferro",
    "Piece of Iron": "Pedaço de Ferro",
    "Piece of Royal Steel": "Pedaço de Aço Real",
    "Piece of Hell Steel": "Pedaço de Aço Infernal",
    "Piece of Draconian Steel": "Pedaço de Aço Draconiano",
    "Huge Chunk of Crude Iron": "Pedaço Enorme de Ferro Bruto",
    "Perfect Behemoth Fang": "Dente de Beemote Perfeito",
    "Piece of Scarab Shell": "Pedaço de Casco de Escaravelho",
    "Spider Silk": "Seda de Aranha",
    "Spool of Yarn": "Carretel de Fio",
    "Ape Fur": "Pele de Macaco",
    "Badger Fur": "Pele de Texugo",
    "Lizard Leather": "Couro de Lagarto",
    "Green Dragon Leather": "Couro de Dragão Verde",
    "Minotaur Leather": "Couro de Minotauro",
    "Lizard Scale": "Escama de Lagarto",
    "Red Dragon Scale": "Escama de Dragão Vermelho",
    "Skunk Tail": "Rabo de Gambá",
    "Carrion Worm Fang": "Dente de Verme Carniceiro",
    "Elder Bonelord Tentacle": "Tentáculo de Bonelord Ancião",
    "Bony Tail": "Cauda Óssea",
    "Stone Wing": "Asa de Pedra",
    "Piece of Crocodile Leather": "Pedaço de Couro de Crocodilo",
    "Giant Eye": "Olho Gigante",
    "Tarantula Egg": "Ovo de Tarântula",
    "Hydra Head": "Cabeça de Hidra",
    "Half Digested Piece of Meat": "Pedaço de Carne Semidigerido",
    "Terrorbird Beak": "Bico de Terrorbird",
    "Skunk Tail": "Rabo de Gambá",
    "Brimstone Fangs": "Presas de Enxofre",
    "Brimstone Shell": "Casco de Enxofre",
    "Sabretooth": "Dente de Sabre",
    "Scythe Leg": "Perna de Foice",
    "Winged Tail": "Cauda Alada",
    "Nettle Blossom": "Flor de Urtiga",
    "Sulphurous Stone": "Pedra Sulfurosa",
    "Unholy Bone": "Osso Profano",
    "Werewolf Fur": "Pele de Lobisomem",
    "Warwolf Fur": "Pele de Lobo de Guerra",
    "Wool": "Lã",
    "Book of Necromantic Rituals": "Livro de Rituais Necromânticos",
    "Dark Lord's Cape": "Capa do Senhor das Trevas",
    "Robe of the Ice Queen": "Túnica da Rainha do Gelo",
    "Dragon Robe": "Túnica do Dragão",
    "Velvet Mantle": "Manto de Veludo",
    "Greenwood Coat": "Casaco de Mata Verde",
    "Hibiscus Dress": "Vestido de Hibisco",
    "Summer Dress": "Vestido de Verão",
    "Tunic": "Túnica",
    "Girls Dress": "Vestido de Menina",
    "Mammoth Fur Cape": "Capa de Pele de Mamute",
    "Mammoth Fur Shorts": "Shorts de Pele de Mamute",
    "Fur Cap": "Gorro de Pele",
    "Pair of Earmuffs": "Par de Protetores de Ouvido",
    "Norse Shield": "Escudo Nórdico",
    "Krimhorn Helmet": "Capacete Krimhorn",
    "Ragnir Helmet": "Capacete Ragnir",
    "Lightning Robe": "Túnica de Raio",
    "Magma Coat": "Casaco de Magma",
    "Magma Monocle": "Monóculo de Magma",
    "Lightning Headband": "Faixa de Raio",
    "Glacier Mask": "Máscara do Glaciar",
    "Terra Hood": "Capuz de Terra",
    "Cobra Hood": "Capuz de Naja",

    # ===== PAREDES, PISOS E CONSTRUÇÕES (Walls, Floors & Constructions) =====
    "Stone Wall": "Parede de Pedra",
    "Wooden Wall": "Parede de Madeira",
    "Brick Wall": "Parede de Tijolos",
    "Marble Floor": "Piso de Mármore",
    "Wooden Floor": "Piso de Madeira",
    "Stone Floor": "Piso de Pedra",
    "Cobbled Pavement": "Pavimento de Pedras",
    "Dirt": "Terra",
    "Grass": "Grama",
    "Sand": "Areia",
    "Shallow Water": "Água Rasa",
    "Lava": "Lava",
    "Ice": "Gelo",
    "Snow": "Neve",
    "Swamp": "Pântano",
    "Tar": "Piche",
    "Mud": "Lama",
    "Earth": "Terra",
    "Stone Stairs": "Escadaria de Pedra",
    "Ladder": "Escada",
    "Ramp": "Rampa",
    "Hole": "Buraco",
    "Trapdoor": "Alçapão",
    "Sewer Grate": "Grelha de Esgoto",
    "Gate of Expertise": "Portão da Mestria",
    "Closed Door": "Porta Fechada",
    "Open Door": "Porta Aberta",
    "Door": "Porta",
    "Window": "Janela",
    "Roof": "Telhado",
    "Cave Entrance": "Entrada da Caverna",
    "Bridge": "Ponte",
    "Fence": "Cerca",
    "Archway": "Arco",
    "Palisade": "Paliçada",
    "Drawbridge": "Ponte Levadiça",
    "Mountain": "Montanha",
    "Tree": "Árvore",
    "Palm": "Palmeira",
    "Fir Tree": "Abeto",
    "Willow": "Salgueiro",
    "Beech": "Faia",
    "Birch": "Bétula",
    "Cactus": "Cacto",
    "Bush": "Arbusto",
    "Flowers": "Flores",
    "Sign": "Placa",
    "Street Sign": "Placa de Rua",
    "Tombstone": "Lápide",
    "Coffin": "Caixão",
    "Campfire": "Fogueira",
    "Magic Forcefield": "Campo de Força Mágico",
    "Vortex": "Vórtex",
    "Teleport": "Teletransporte",
    "Portal": "Portal",
    "Mystic Flame": "Chama Mística",
    "Obsidian Pipes": "Tubulações de Obsidiana",
    "Energy Field": "Campo de Energia",
    "Fire Field": "Campo de Fogo",
    "Poison Field": "Campo Venenoso",
    "Smoke": "Fumaça",
    "Ashes": "Cinzas",
    "Blood": "Sangue",
    "Bloodstain": "Mancha de Sangue",
    "Cobwebs": "Teias de Aranha",
    "Web": "Teia",
    "Spider Web": "Teia de Aranha",
    "Candelabrum": "Candelabro",
    "Candle": "Vela",
    "Lamp": "Luminária",
    "Lit Lamp": "Luminária Acesa",
    "Torch": "Tocha",
    "Coal Basin": "Braseiro",
    "Fireplace": "Lareira",
    "Relic of the Abyss": "Relíquia do Abismo",
    "Dark Ruined Wall": "Parede Escura em Ruínas",
}