# mcr — Pacote fundamental do ecossistema MCR-DevIA
from mcr.paths import (
    ROOT_DIR, SERVER_DIR, CANARY_SRC_DIR, CANARY_SCRIPTS_DIR,
    CANARY_DATA_DIR, CANARY_NPC_DIR, CANARY_MONSTER_DIR, CANARY_ITEMS_XML,
    CLIENT_DIR, DEVIA_DIR, DEVIA_KERNEL_DIR, DEVIA_MODULES_DIR,
    DEVIA_COMANDOS_DIR, DEVIA_KNOWLEDGE_DIR,
    KG_DIR, DATA_DIR, GENERATED_DIR, CACHE_DIR,
    SCRIPTS_GENERATED_DIR, SCRIPTS_QUARANTINE_DIR,
    GOLDEN_EXAMPLES_DIR, DOCS_DIR, LORE_DIR,
    TOOLS_DIR, GRIMORIO_DIR, LOGIN_SERVER_DIR, MAP_EDITOR_DIR,
    PROTOTYPES_DIR, SANDBOX_DIR, SCRIPTS_DIR,
    SANDBOX_CRIATIVO_DIR, IDEAS_DIR,
    ROUTER_CACHE, MCR_PY,
    ensure_dirs,
)
from mcr.encoding import read_file, write_file, read_lines, write_lines
