-- NPC gerado pelo MCR Crew v11
-- NOME: Ferreiro
-- SAUDACAO: "Olá, bem-vindo ao meu forjão! Como posso ajudar você hoje?"
-- ITENS: 1002:50, 1003:75, 1041:100
-- DIALOGOS:
-- "Você está procurando algum objeto de metal?" -> "Sim, tenho vários itens disponíveis!"
-- "Qual é o preço do cobre?" -> "O cobre custa 50 moedas."
-- "Podemos negociar o preço?" -> "Claro, posso oferecer um desconto para você."
-- "O que você pode fazer aqui?" -> "Eu consigo forjar armas e ferramentas!"
-- "Você está trabalhando em uma nova criação?" -> "Sim, estou experimentando alguns novos materiais!"
-- "Bom trabalho, Ferreiro! Obrigado pela ajuda!" -> "De nada, sempre à disposição!"
